### PR TITLE
FIX : Fixed get user blogs and gitignore file. 

### PR DESCRIPTION
**Pull request by Ayush-Vish**

### CODE REVIEW

**Comment by Ayush-Vish** [comment]
@sidjaiswal2003  If any other change in code is needed, Please let me know.

**Comment by sidjaiswal2003** [comment]
@Ayush-Vish  Still i am getting error failed to fetch . Its seems like the error is in PostsWidget,jsx .

**Review by sidjaiswal2003 — COMMENTED** [review]
Error  not resolved

**Comment by Ayush-Vish** [comment]
> @Ayush-Vish Still i am getting error failed to fetch . Its seems like the error is in PostsWidget,jsx .

Ok I'll Fix that.

**Pull request closed without merging**
